### ISSUE TITLE
How can i manual setup 4.24 vision plugin?

### ISSUE THREAD

**Issue by Andante-1** [ValveSoftware/steamvr_unreal_plugin#109]
Hi, 
i was download 4.24 vision file 
but i don't know how to manual setup.
i was trying copy to project consent file but not active icon.
please help me! 
![Q](https://user-images.githubusercontent.com/55864628/72117696-088e3280-3392-11ea-8601-aaea93353490.PNG)

**Comment by 1runeberg** [comment]
Hi @Andante-1

Not sure I understand the issue - but from the screenshot, it seems that you don't have the SteamVR Plugin enabled or you are using Oculus Hardware.

If you are using Oculus Hardware, you need to disable the Engine's Oculus Plugin so SteamVR can handle the input and rendering. You can also switch the HMD priorities, but simply disabling the Oculus Plugin temporarily for SteamVR development with Oculus Hardware is faster/easier.

Otherwise, if you can elaborate a bit further on the following:

(a) Expected Outcome
(b) What you have tried already
(c) Detailed issue or configuration question

I'd also suggest having a look at our Sample Project here:
https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin_UEIntegrated.7z

Or try using the Sample VR Template and see if that is at least working in your system.

Let me know.

Cheers,
Rune

**Comment by Andante-1** [comment]
Hi 1runberg

Thank you for your support.

a) I have disabled the Oculus plugin but nothing happens.
b) My installation method migrated the contents of the sample file to the My project.
Is this the right way?
c)  My project was created in version 4.24, so I need the correct installation of the current plugin.

Thank you :>

**Comment by 1runeberg** [comment]
Hi @Andante-1 - Can you provide me the link to where you got the assets you are migrating to your 4.24 project?

**Comment by 1runeberg** [comment]
Hi @Andante-1 - do you still need help on this? Let us know!

**Comment by kisak-valve** [comment]
Closing pending feedback.
