### ISSUE TITLE
Vive Trackpad Touch Bindings (UE4 Side) become Press/Click bindings (SteamVR Input Side)

### ISSUE THREAD

**Issue by smapty** [ValveSoftware/steamvr_unreal_plugin#11]
There's an issue right now that if you select a touch input binding (in the input preferences within the UE4 editor), that binding will become a click in the SteamVR Input binding when you generate the controller bindings.

A quick change to SteamVRInputDevice.cpp:1435...
From
`InputState.bIsCapSense = CurrentInputKeyName.Contains(TEXT("CapSense"), ESearchCase::CaseSensitive, ESearchDir::FromEnd)`
To
`InputState.bIsCapSense = CurrentInputKeyName.Contains(TEXT("CapSense"), ESearchCase::CaseSensitive, ESearchDir::FromEnd) || CurrentInputKeyName.Contains(TEXT("Touch"), ESearchCase::CaseSensitive, ESearchDir::FromEnd);`

Fixes the issue.

**Comment by 1runeberg** [comment]
This is now fixed in develop branch.

Included your change and added extra processing to ensure Oculus keys get processed correctly as well. Thanks for reporting!

This will be included in the next release. I'm including you to the credits list, let me know if this is an issue for you or if you want a specific name to be listed other than @smapty :)

**Comment by smapty** [comment]
Karl Johnson would be awesome for credits! :)
