### ISSUE TITLE
UE 4.24.3 New project VR Template - Vive controller does not track

### ISSUE THREAD

**Issue by sobin-hyperreality** [ValveSoftware/steamvr_unreal_plugin#133]
Have different behavior on 2 machines. On one machine - create a new project with VR template. Vive controller does not track and lies on the floor. On another it works. Am using Steam VR 1.9.16 . 

Have ensured that : 
- SteamVRBindings under Config has been regenrated. 
- Tried regenerating , reloading action manifest etc...no use
- Quit / relaunch / restarted system - no use
- Added new bindings to the default ones. 
- Made sure Oculus VR plugin is turned off . Also tried enabling/disabling SteamVRInput controller. 

This is critical for us as it is not easy for us to downgrade the project now.

**Comment by 1runeberg** [comment]
Hi @sobin-hyperreality - Is this a vanilla UE4 VR Template? Are there any other plugins that may be using the Input System?

In the logs or the console output, can you check if the loading of the Action Manifest returned a success?

**Comment by Fidom** [comment]
> Have different behavior on 2 machines. On one machine - create a new project with VR template. Vive controller does not track and lies on the floor. On another it works. Am using Steam VR 1.9.16 .
> 
> Have ensured that :
> 
> * SteamVRBindings under Config has been regenrated.
> * Tried regenerating , reloading action manifest etc...no use
> * Quit / relaunch / restarted system - no use
> * Added new bindings to the default ones.
> * Made sure Oculus VR plugin is turned off . Also tried enabling/disabling SteamVRInput controller.
> 
> This is critical for us as it is not easy for us to downgrade the project now.

I have the same problem. When i enable Steam VR the UE4 Template the controllers are on the ground. If i disable steam vr its working but the controllers are not matched with the my own controller. They are on a distances based on the position in start. Its not finding the start position of the controllers

Update:

The standerd unreal engine template is not working but the steam vr sample project is.

**Comment by 1runeberg** [comment]
> > Have different behavior on 2 machines. On one machine - create a new project with VR template. Vive controller does not track and lies on the floor. On another it works. Am using Steam VR 1.9.16 .
> > Have ensured that :
> > 
> > * SteamVRBindings under Config has been regenrated.
> > * Tried regenerating , reloading action manifest etc...no use
> > * Quit / relaunch / restarted system - no use
> > * Added new bindings to the default ones.
> > * Made sure Oculus VR plugin is turned off . Also tried enabling/disabling SteamVRInput controller.
> > 
> > This is critical for us as it is not easy for us to downgrade the project now.
> 
> I have the same problem. When i enable Steam VR the UE4 Template the controllers are on the ground. If i disable steam vr its working but the controllers are not matched with the my own controller. They are on a distances based on the position in start. Its not finding the start position of the controllers
> 
> Update:
> 
> The standerd unreal engine template is not working but the steam vr sample project is.

Hi @Fidom - which version of the plugin are you using? Can you send over your raw UE4 logs for the raw UE4 template?

**Comment by Fidom** [comment]
> > > Have different behavior on 2 machines. On one machine - create a new project with VR template. Vive controller does not track and lies on the floor. On another it works. Am using Steam VR 1.9.16 .
> > > Have ensured that :
> > > 
> > > * SteamVRBindings under Config has been regenrated.
> > > * Tried regenerating , reloading action manifest etc...no use
> > > * Quit / relaunch / restarted system - no use
> > > * Added new bindings to the default ones.
> > > * Made sure Oculus VR plugin is turned off . Also tried enabling/disabling SteamVRInput controller.
> > > 
> > > This is critical for us as it is not easy for us to downgrade the project now.
> > 
> > 
> > I have the same problem. When i enable Steam VR the UE4 Template the controllers are on the ground. If i disable steam vr its working but the controllers are not matched with the my own controller. They are on a distances based on the position in start. Its not finding the start position of the controllers
> > Update:
> > The standerd unreal engine template is not working but the steam vr sample project is.
> 
> Hi @Fidom - which version of the plugin are you using? Can you send over your raw UE4 logs for the raw UE4 template?

Hee tanks for helping. I got it working with the other template. But for developing purpose:

I'm using UE 4.23.1 and have Microsoft mixed reality and use it with SteamVR

I made a video and have the logs here:

[UE_Log.txt](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/4371854/UE_Log.txt)
Video: https://drive.google.com/open?id=1J2nqOg4IuuYEUuxjI3NHaEd4Z6Gm3PL8

**Comment by 1runeberg** [comment]
Hi @Fidom thanks for the logs, can you try the following (in order):

(1) Go to your %APPDATA%\Local and check if you have MyProject2 there, and delete it if it exists. Then try running the project again. 

If an old MyProject2 was created before in this machine before and didnt have the correct bindings (e.g. was based on a non-VR Template, it may be loading that manifest instead of the new project).

(2) Failing that, can you try creating a new VR Template project and name it something unique, put a name as well on "Project Name" in the Project Settings. 

(3)  Go to your {X}:\Program Files (x86)\Steam\config\steamvr.vrsettings file and delete any entry here with "ue" on it. you can also delete this file (all your steamvr settings will revert to defaults).

(4) Try renaming "Unreal Projects" directory to "UnrealProjects" (without spaces)

(5) If all of the above still fails, send me the UE4 logs taken during the video and a SteamVR System Report. This may have some sensitive info, so you can send it to runeb@valvesoftware.com

Thanks.

**Comment by 1runeberg** [comment]
hi @Fidom - are you still having issues with WMR?

**Comment by Fidom** [comment]
Hee Rune,

No I'm not I used the template from steam vr it's all working great, but
with the standard but template form unreal it's not working with the steam
vr enabled. I don't care because it's working but maybe for other users
it's can be a problem. I would like to help you with giving feedback if you
like.

Met vriendelijke groet,


Fido Melskens


0653210361
