### ISSUE TITLE
Failed to Load SteamVR Inpu Anim Pose Node in BP

### ISSUE THREAD

**Issue by briandrehoff** [ValveSoftware/steamvr_unreal_plugin#138]
As of 4.25 Preview 5 (possibly also happens with previous engine versions) the node for automatically generating finger movement in BP "SteamVR Skeletal Anim Pose" works fine, but upon reopening the project it says it cannot be found and it disappears from the AnimGraph needing to be replaced again to get it working. Is there a solution or a workaround to this problem? It seems like the plugin is now built into UE4.

**Comment by 1runeberg** [comment]
Hi @briandrehoff - The plugin has been integrated since version 4.24

Are you upgrading from 4.23? 

Migrating from Marketplace to the integrated version, you normally just need to delete your Intermediate and Saved folders for your project and allow UE4 to recreate them to remove any old references to the nodes from the Marketplace version.

We also have a different sample project for the integrated version as the sample content isn't included in the integrated version, so these are now just regular project assets here:
https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin_UEIntegrated.7z

**Comment by 1runeberg** [comment]
@briandrehoff - Hi, any updates on this, are you still having issues?

**Comment by briandrehoff** [comment]
Sorry didn't see your response. I ended up just creating my own finger bends so it would stop disappearing. I have upgraded from 4.23 and am now at 4.25.1. I will have to give that node a try again to see if the issue persists or not.

**Comment by simongloor** [comment]
Yes, the problem still exists in 4.25.3.

I've had this issue in a side project for almost about a year now. It seems to be caused by the loading order of the SteamVR plugin and my own plugin, as I managed to fix it in some versions that had a different loading order.

My last, incomplete attempt on solving this was to create my own AnimGraphNode. That still seems to be unnecessary complicated though.

**Comment by 1runeberg** [comment]
Hi @simongloor- the loading phase is intentional for this plugin. Any other plugins that need to consume this plugin or use it needs to load later. We can't load the plugin earlier due to engine xr achitecture considerations.
