### ISSUE TITLE
Axis binding SteamVr 

### ISSUE THREAD

**Issue by Azool2** [ValveSoftware/steamvr_unreal_plugin#197]
Here are my issues with Steam VR Axis binding: 
https://youtu.be/JSdHVT8JOEI

Thank you for your time.

**Comment by 1runeberg** [comment]
Hi @Azool2 - sorry about the delayed response, I somehow missed the github notification for this issue.

Anyways, really appreciate the detailed report you sent. In the video, at 1:42, it seems like you've got your personal input bindings enabled and not the default one that the engine is sending:

![image](https://user-images.githubusercontent.com/17371351/204865777-5e0a975e-d9ec-4488-827c-40891a527a73.png)

You need to activate the default bindings from the project. Let me know how that goes.

Cheers,
Rune

**Comment by Azool2** [comment]
Dear Rune, thank you very much for your reply. 
Unfortunately, that is not the problem, and it can't be the problem, otherwise I would have found it long ago. 

![01](https://user-images.githubusercontent.com/78986510/205179914-e39e57ec-439f-4207-90aa-ea459db343d4.jpg)
![02](https://user-images.githubusercontent.com/78986510/205179939-7b5552f4-0126-4463-8ef7-ad2b23056ce8.jpg)

I'm going to record a video this weekend to show it. 
I'm looking forward to your answer. 
thank you again for your time, Rune. 
Cheers, 
Armin

**Comment by Azool2** [comment]
https://youtu.be/6ao5OhQEu8U
I record a new video. 
Thank you. 
Let me know if you see a problem. 
Thanks.

**Comment by 1runeberg** [comment]
Hi @Azool2  - Thanks for the update. 

You need to create a "pair" for thumbstick and trackpad bindings. This is because steamvr uses vector2 (float, float) actions while UE (outside of the new enhanced input system) only supports vector1 (float) bindings,

So in UE, if you create a MOVE_Y action that is bound to ThumbstickY, you need to also create a MOVE_X action that is bound to ThumbstickX. The steamvr input plugin will then recognize what you're trying to do and create behind the scenes a vector2 action to send to steamvr.

For the plugin to recognize you want a vector2 action:

- Make sure the naming is the same for the actions you want to pair - e.g. MOVE_X, MOVE_Y  and not MOVE_X, MOVE_SOMEHTING_Y

- Also, ensure that the suffix of the action name is _X and _Y (with the underscore) 

If you're still having issues after checking the above, send me a minimal repro project and I can have a closer look.

Cheers,
Rune

**Comment by Azool2** [comment]
Thank you, Rune, that was exactly the problem. We have to make 2 _Y and _X. 
Thank you for your time. 
Best Regards 
Armin

**Comment by 1runeberg** [comment]
Awesome! Glad that worked out :)
