### ISSUE TITLE
Switch out vr gloves for custom mesh and rig

### ISSUE THREAD

**Issue by tedconry** [ValveSoftware/steamvr_unreal_plugin#71]
Hey, I need to switch the default vr gloves for my custom mesh. I'm having trouble getting the animation to re target. I've taken the default steam vr gloves into Maya and lined them up with my mesh and duplicated the rig from the steam vr ( to get the same orientation) and applied it to my mesh. Now, in Unreal real engine 4, I tried to re target the animation and I'm getting bad results. I tried to re target based on skeleton but that didn't work either. Is it possible to switch out the animation or the rig and mesh while keeping the steam vr input plugin functionality?
![glove](https://user-images.githubusercontent.com/55997487/65915711-30342e80-e391-11e9-9cd6-12079a335cf1.jpg)

**Comment by 1runeberg** [comment]
If you just want to reuse the sample content, you can do a re-import of the mesh after your changes in Maya (may not work properly if mesh is substantially different or not based on the original steamvr fbx):

![2019-09-30 16_21_36-Window](https://user-images.githubusercontent.com/17371351/65924097-0f270a00-e3a0-11e9-9b92-eda9a639a23c.png)

However, it is best to re-implement the code (for live animation) or create your own poses/anims as we did not intend for the sample content to be reuseable.

This is the node you need in your anim graph to get the skeletal/finger anims:
![2019-09-30 18_43_39-Window](https://user-images.githubusercontent.com/17371351/65928341-6f26ac00-e3b2-11e9-994a-efbf7d582d31.png)

**Comment by tedconry** [comment]
ok, How do I get my rig and my mesh into to use in your plugin?

**Comment by tedconry** [comment]
Also, all the rig information has to be the same in order for the plugin to work?The root bone  is scaled at 100 (meter to cm conversion) and the fingers have different orientation than the rest of bones. I want to make sure that the rig  is built right in order to to use your plugin.

**Comment by 1runeberg** [comment]
Hi @tedconry - you need to rig your mesh based on the SteamVR skeleton, original sample fbx can be found in your system at:
C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\skeletons

or you can also use the UE4 hand skeleton that comes with the Unreal Engine VR Template (if you look at the node in my previous post, there's a dropdown where you can select the skeleton type).

the plugin does a hard check for the number of bones and uses the bone names to drive the animation pose. ideally, use the provided skeletons and reimport skinned to your own mesh to unreal. dont change any of the scales, they are accounted for by the animation node we provided.

If it helps, I've also made a (unofficial) tutorial as part of my community work, about skeletal anims here:
https://www.youtube.com/watch?v=OJk-KB_8i_c

There's a part there that I demoed a way to use a nonstandard skeleton (taken from RoboRecall modkit assets),  the anim is driven by finger curl values instead of raw vector3s.

hope that helps!

**Comment by tedconry** [comment]
Yeah,that worked. Thanks for the quick reply and all the information. You're a life saver.

**Comment by tedconry** [comment]
I'm running into a problem with UE 4 vr gloves joints. Can I use the joints for the left and right gloves? In the default there is only a right glove that's mirrored. Do I have to mirror the glove? If don't have to, than how should I orient the joints?

**Comment by 1runeberg** [comment]
Opened a new issue for the UE4 VR gloves
