### ISSUE TITLE
4.22 and SteamVR 1.7.15

### ISSUE THREAD

**Issue by zoshua** [ValveSoftware/steamvr_unreal_plugin#73]
Hi,

I wanted to know if I should expect a fresh setup in 4.22 to work with SteamVR 1.7.15

I am seeing the sample project in 4.23 work no problem.

However I am having no luck trying to connect things up in simple 4.22 project.

Help!

Thanks.

+z

**Comment by 1runeberg** [comment]
Hi @zoshua - We'll likely update the plugin on the next release to a later version of SteamVR (currently it's at 1.5.17). We're just ensuring everything is stable while in parity with the Unreal Engine built-in OpenVR. Hopefully in the next couple of weeks.

Was there a particular feature in 1.7.15 you were after?

**Comment by CybershoesVR** [comment]
Hello @1runeberg - We're also working with UE4.23, but it doesn't seem to work at all. We're making Cybershoes, a VR-Treadmill that relies heavily on SteamVR Input, so we would also really appreciate this update.

As a feature request: We would be happy if a game dev that works on UE can easily wire up a treadmill controller with the input action of choice.

**Comment by 1runeberg** [comment]
Hi @CybershoesVR - not sure what issue you're referring to here? (related to this ticket)

**Comment by CybershoesVR** [comment]
@1runeberg - We're on the newest version of SteamVR. Both the SteamVR and the SteamVR Input Plugin are included in the project. Our base was Epic's VR Template that's available from the Unreal Launcher.

**What we see:**
The game works the same as before we added the plugin.

**What we got:**
The binding .json files have been created with the previously used bindings.
The unreal default bindings have also been expanded with what looks like legacy support:
Instead of just "Motion Controller" actions, there are additional bindings for every kind of controller.

**What doesn't work:**
None of the Editor Buttons seem to do anything (No matter in what order). 
We also can't access the SteamVR Dashboard (Neither in-game or through the editor).
There are warnings all over the example blueprints (all connected to input events).

(We will make a new issue for our feature request, sorry).

**Comment by 1runeberg** [comment]
Hi @CybershoesVR - This issue is for SteamVR 1.7.15 - can you also open a new issue please for the problem you are having with your project?

A good place to start though if you haven't already is the QuickStart in our Wiki:
https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/Quickstart

**Comment by 1runeberg** [comment]
Closing for now, please reopen if you have any more questions on this. thanks.

(Treadmill source in another issue)
