### ISSUE TITLE
Manual binding doesn't work with Valve Index for Ue4.22

### ISSUE THREAD

**Issue by Kucki2018** [ValveSoftware/steamvr_unreal_plugin#78]
Hey,

The Sample Project works fine but if I add another binding to it and click these 3 things in the toolbar (regeneration etc.) then the new Action or axis input isn't getting recognized. It doesn't matter which button. 

I also tried the Trigger Axis - exactly like in this Video: https://www.youtube.com/watch?v=oi93qXgNBjk&list=PLngZ5l9HmlORHi2E1UzxPxD6BnXHyZ6M0&index=5

But it won't show up inside the Dashboard (sometimes I even have problems opening the dashboard, but when it does - it only shows the sample project inputs and NOT the one I just added) and the value will stay at zero.

**Comment by 1runeberg** [comment]
Hi @kucki2018 - which version of the SteamVR runtime are you on? Also specifically, which controller buttons have you added?

Cheers,
Rune

**Comment by Kucki2018** [comment]
I am using 1.8.13 and I tried to bind a lot of Valve Index buttons or even MotionController buttons like:

Valve Index Thumbstick Pressed, Trigger Pressed, Grip Pressed, or Axis Events like: Valve Index Thumbstick X, Y and I even tried to redo the Sample Inputs like: Valve Index GripGrab. 
Or Motioncontroller Trigger Axis - I did it exactly like in your Video (https://www.youtube.com/watch?v=oi93qXgNBjk&list=PLngZ5l9HmlORHi2E1UzxPxD6BnXHyZ6M0&index=5)

*I am using the Marketplace version - should I download the Github version instead?

**Comment by 1runeberg** [comment]
With 1.8.13 (beta), the dashboard will not work due to recent changes in steamvr.  in themeantime, call the dashboard ui from the runtime for your debugging.

can you send over the follwing to me please:

(1) DefaultInput.ini
(2) .uproject file
(3) Logs under the Saved directory
(4) Everything under Config\SteamVRBindings

runeb@valvesoftware.com

**Comment by Kucki2018** [comment]
Hey, 
I sent the e-mail.

**Comment by 1runeberg** [comment]
Hi - the bindings appear to be bound properly. But you have a large number of BP errors with your player character and seem to be related to the Motioncontroller/hands? have you investigated the cause of this issue in your project?

if you feel this isn't related. can you try the vanilla sample project here:

https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin.zip

and add the same bindings. if you are still getting the errors, can you send over the same files to me for this sample project instead?

thanks.

**Comment by Kucki2018** [comment]
Hey,
Yeah, those errors are from the old Pawn that I haven't deleted yet because I thought that I may need it later :D

Okay, everything worked inside the Sample Project you sent me (Ue4.22). But when I try the 4.21 Sample Project, Input like "Motion controller (R) Trigger" gets recognized but input from a specific target like "Valve Index (R) Trigger Press" not. 

I think I will do a fresh start and reinstall the plugin. Should I also clear the "DefaultInput.ini" besides deleting "SteamVRBindings" and "steamvr_ue_editor_app". Do you have any guide about how to delete the plugin?

**Comment by 1runeberg** [comment]
Hi - OK, just note the BP errors are happening during runtime so it must be active in your level.

To delete the marketplace version of the plugin, use the Epic Launcher:

(1) Open Epic Launcher
(2) Click on "Unreal Engine" in the lefthand menu
(3) Click on the "Library" tab 
(4) Clicked on "Installed Plugins"
(5) Click "Remove" button beside "SteamVR Input Plugin"

Note that projects relyign on the plugin may not work once the plugin is uninstalled.

On the project level, there is no need to remove DefaultInput.ini. You can delete SteamVRBindings if you havent created any custom bindings via the SteamVR Dashboard, otherwise, make sure you have a backup of the files here. 

The "steamvr_ue_editor_app.json" file can be safely deleted.

Please note also, the built-in UE MotionController keys will ONLY work if there are no other SteamVR keys defined under the same action. I believe I mentioned this as well in hte unofficial tutorial video you quoted here. 

The MotionController keys will generate bindings for all known controllers - this is not suggested for the Facebutton though as not all controllers have "facebuttons" as such.

I hope that helps.

Cheers,
Rune

**Comment by Kucki2018** [comment]
![Unbenannt](https://user-images.githubusercontent.com/43949430/67143184-f1471980-f268-11e9-89f9-755f0df07e66.PNG)
 So, I still run into some problems. When testing your Sample Project (the one you sent me yesterday, fresh and new) the blue circled things (Screenshot) work and the red circled thing not. 

When testing in my own project, just the Grabbing works and the other "Sample Inputs" like MoveLeft_X/Y or MoveRight_X/Y not.

I emailed you the following from your Sample Project: (Ue4.22)
(1) DefaultInput.ini
(2) .uproject file
(3) Logs under the Saved directory
(4) Everything under Config\SteamVRBindings


Edit: After further testing around this problem - I added some more input (Axis and Action) and now the "MotionController (R) Trigger" seems working (which didn't work before) but the "MotionController (L) Thumbstick X" not. 

![Unbenannt](https://user-images.githubusercontent.com/43949430/67143728-90224480-f26e-11e9-92ca-7df8d799740a.PNG)

**Comment by 1runeberg** [comment]
Hi @Kucki2018 - How are you testing the new actions?

**Comment by Kucki2018** [comment]
I add the Input to my Character and print a string if the button is pressed or the value changes (Axis). Just like you did in the Video (https://www.youtube.com/watch?v=oi93qXgNBjk&list=PLngZ5l9HmlORHi2E1UzxPxD6BnXHyZ6M0&index=5) but with "Print String" instead of a Text Render.

**Comment by 1runeberg** [comment]
@Kucki2018 - Is this the character class from the sample project? If so, can you re-zip the sample project (excluding Binaries, Intermediate, Saved and Build folders) and send them over to me and I can have a quick look on the Action Events in BP that you have.

Please  only the  vanilla sample project we sent with your attempts to add additional inputs and not your own game or project as we won't be able to troubleshoot custom projects/games. Thanks.

**Comment by Kucki2018** [comment]
Hey,
I just sent the E-Mail.

**Comment by 1runeberg** [comment]
Hi @Kucki2018, thanks for the files.

**(1) Trigger Left/Right:**

I didn't have any issues triggering the Right trigger - depending on your machine, the resulting "Hello" text may be being drowned out quickly by the Thumbstick X Axis print output. But you can search the Output log or disable the Thumbstick X printing to see that the trigger is indeed being clicked and receiving input.

As for the Left Trigger, there was no corresponding action in your BP, if you add something like this:

![image](https://user-images.githubusercontent.com/17371351/67152007-b1d9f680-f283-11e9-8d36-9bd0ef9eec84.png)

Then you should get the debug output you're expecting. Something else to note is in the SteamVR Input dashboard, make sure you're in the correct bindings like this:

![image](https://user-images.githubusercontent.com/17371351/67152020-ddf57780-f283-11e9-8d8f-5b880755211f.png)

... and not on a personal or edited binding from a previous session:
![image](https://user-images.githubusercontent.com/17371351/67152139-ad164200-f285-11e9-9968-a0b01eba8fce.png)

**If you are in an edited version and wish to revert back to default by:**

(1.1) Under "Official Bindings" > "Default bindings for..." click "View"
![image](https://user-images.githubusercontent.com/17371351/67152172-19914100-f286-11e9-8ed4-73d6e69792f7.png)

(1.2) Click "Select this binding at the bottom of the UI:
![image](https://user-images.githubusercontent.com/17371351/67152183-3ded1d80-f286-11e9-8a69-623561a7693e.png)

(1.3) Choose "Discard" or "Save" in the confirmation pop-up:
![image](https://user-images.githubusercontent.com/17371351/67152201-67a64480-f286-11e9-9029-e1ba4ded02f2.png)

**If you don't have the buttons described above, you can enable them in the SteamVR Runtime:**

![image](https://user-images.githubusercontent.com/17371351/67152228-cc619f00-f286-11e9-8236-27792f173190.png)

![image](https://user-images.githubusercontent.com/17371351/67152241-ea2f0400-f286-11e9-83eb-b438b93ea9dc.png)

**(2) Thumbstick Axis**

The reason this is not coming out is that, due to the Unreal Engine not supporting a Vector2 in the bindings UI, you need to satisfy the follwing conditions:

   (a) Make corresponding Thumbstick  X & Y actions. That means you need to have two separate actions, one having Thumbstick/Joystick X, the other Thumbstick/Joystick Y keys

  (b) Names of the actions should end with "_X" and ""_Y" respectively.

  (c) Since different controllers have different naming conventions for the thumbstick (e.g. Index calls it Thumbstick, Oculus calls it as Joystick), it is recommended to add individual controller axes in this case to ensure you're supporting all the controllers you wish to support correctly.

Here's a screenshot of my modifications in BP on the sample you sent:
![image](https://user-images.githubusercontent.com/17371351/67152071-8572aa00-f284-11e9-923e-4f5635d984d4.png)

When you rename your "ThumbstickLeftX" to "ThumbstickLeft_Y" action, make sure you edit your BP accordingly:

![image](https://user-images.githubusercontent.com/17371351/67152094-0f227780-f285-11e9-896f-aa8f491a1999.png)

I hope the above helps, any other questions, just let me know!

Cheers,
Rune

**Comment by Kucki2018** [comment]
I changed some things inside the dashboard. Does that have an effect on my input bindings? If yes, how do I reset them to default?

**Comment by 1runeberg** [comment]
Check out the instructions on 1.1-1.3 I have above.

(you replied before I got my edits in :) )

**Comment by Kucki2018** [comment]
Thanks! Yeah, we are both pretty quick! :D
One more thing: Did you used the Github or Marketplace version?

**Comment by 1runeberg** [comment]
It shouldn't matter, they are the same code. The develop branches in GitHub though have non-fully tested features, so if you're just starting with the new Input System, I suggest keeping to the Marketplace version in the meantime.

I however tested the modified Marketplace version you gave (added BP debug nodes in the Pawn). Ideally, you shouldn't be modifying the sample content directly as your changes can be overwritten anytime the plugin is updated.

**Comment by Kucki2018** [comment]
I figured it out! It was the Dashboard all along... I changed some bindings inside my dashboard and everything stopped working. Well, I switched back to the official bindings and it works like a charm!

Thank you for your help! It's awesome that you'll also work on the weekends. I will remind myself to send you a key (over E-Mail) when my game is out for SteamVR.

Have a nice day :)
