### ISSUE TITLE
When cooking a pc build with the existence of restricted folder names having the the steamvr plugin will cause a staging error

### ISSUE THREAD

**Issue by martinsweitzer** [ValveSoftware/steamvr_unreal_plugin#9]
In SteamVRInput.Build.cs

this line should not exist

      RuntimeDependencies.Add(new RuntimeDependency("$(ProjectDir)/Config/..."));

it forces ALL of the various .ini(s) from say PS4 to be wanted to be staged.  But the PS4 is a restricted directory for win64 and the stage will fail.

**Comment by 1runeberg** [comment]
This is fixed in develop – was there for a patch fix with packaged builds crashing/losing input with some headsets. The change to pure function calls in the current develop branch helps fix stability issues.

Let us know however if the SteamVRBindings subfolder also causes issues with PS4 builds, although ideally the plugin shouldnt be enabled or packaged for any PS4 builds.
