### ISSUE TITLE
How can I find out which controllers a player with HTC is using? Knuckles or not?

### ISSUE THREAD

**Issue by Wazzdaka** [ValveSoftware/steamvr_unreal_plugin#97]
I figured out your plugin. Inputs for Oculus, HTC and WMR work for me. One problem remains. How can I find out which controllers a player with HTC is using? Knuckles or not?

**Comment by 1runeberg** [comment]
Hi @Wazzdaka,

You can use the below node on an Axis Action you have in your project. In the screenshot below we used the "SqueezeLeft" action from the sample project:

![image](https://user-images.githubusercontent.com/17371351/70083046-ca4d7700-165f-11ea-84e8-548f02a95f35.png)

Just remember to add the word "axis" at the end of the action name you defined in the Input Settings.

**Comment by 1runeberg** [comment]
Closing issue for now, please re-open if you have any issue.

There Sample Project updated yesterday also has a sample of this functionality implemented:
https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin_UEIntegrated.7z

**Comment by 1runeberg** [comment]
If anyone else is seeing further problems with this, just let us know and we can re-open this issue report :)

Cheers,
Rune

**Comment by badVibes--** [comment]
Could you guys please solve this in a more elegant way. What am I supposed to do until the user touches the selected axis? I have to change the controller mesh depending on which controller the user has and not displaying anything until they touch something feels like a bug. I haven't seen one game that starts with 'please press a button so we know what controller you have'.  It just seems silly. 

You need to work with Epic to add an event that triggers when this information becomes available. 
Thank you.

**Comment by 1runeberg** [comment]
Hi @badVibes-- Have you tried the FindSteamVR_InputBindingInfo and GetSteamVR_InputBindingInfo nodes? They don't require a prior input.

SteamVRInput is an actions-based system and isn't controller-based, ideally applications shouldn't need the controller type so there's no direct way to query a controller type. 

But the above nodes should report information about the action and which controller the runtime detected in a given user session, so you can use it that way to extract controller type if you need to.

**Comment by badVibes--** [comment]
I looked at the nodes you mentioned and do not understand how exactly I am supposed to extract the needed information from the output they give. Some kind of dummy action definition?

"ideally applications shouldn't need the controller type so there's no direct way to query a controller type"   I need it to display a mesh of the controller (with tooltips). Its a drawing app and just displaying animated palms doesn't work.  It's frustrating because this information is obviously available, you just decided not to expose it. It's great that you guys want to unify things but sometimes they can just not be unified in a practical way.

**Comment by badVibes--** [comment]
Well, in the end i was able to get the info from bindings to axis inputs fast enough. Thank you for your suggestions.
